import React, { useMemo } from 'react';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import { Sigma } from 'lucide-react';

interface MathEquationProps {
  formula: string;
  displayMode?: boolean;
}

const MathEquation: React.FC<MathEquationProps> = ({ formula, displayMode = true }) => {
  const html = useMemo(() => {
    try {
      return katex.renderToString(formula, {
        displayMode,
        throwOnError: false,
      });
    } catch (e) {
      return formula;
    }
  }, [formula, displayMode]);

  return (
    <div
      dangerouslySetInnerHTML={{ __html: html }}
      className={`overflow-x-auto ${displayMode ? 'py-2 text-[#00f0ff]' : 'inline-block text-[#00f0ff]'}`}
    />
  );
};

export const MathFormulation: React.FC = () => {
  return (
    <section className="relative w-full py-24 px-6 md:px-12 z-10 border-t border-white/[0.08] bg-[#03070d] select-none">
      <div className="max-w-6xl mx-auto space-y-12">
        {/* Section Header */}
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2 text-[#00f0ff] uppercase tracking-widest text-[11px] font-mono">
            <Sigma className="w-4 h-4" />
            <span>MATHEMATICAL FOUNDATIONS & PROOFS</span>
          </div>
          <h2 className="font-sans text-3xl sm:text-4xl font-bold text-white tracking-tight">
            Electromagnetic Wave Mechanics & Cumulant Tensors
          </h2>
          <p className="text-sm text-slate-400 font-sans max-w-2xl leading-relaxed">
            Formal mathematical equations governing spatial GLSL displacement, blind statistical modulation moments, and Galois Field rank deficiency.
          </p>
        </div>

        {/* 4 Formulation Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Equation 1: Damped Wave Equation */}
          <div className="bg-white/[0.02] border border-white/[0.08] p-6 rounded-xl space-y-3 font-mono text-xs">
            <div className="text-[10px] text-slate-400 uppercase tracking-widest border-b border-white/10 pb-2 flex justify-between font-mono">
              <span>THEOREM 1.0</span>
              <span className="text-[#00f0ff]">DAMPED WAVE PDE</span>
            </div>
            <p className="text-slate-300 font-sans leading-relaxed text-xs">
              The continuous field satisfies the second-order partial differential wave equation with viscous attenuation:
            </p>
            <div className="bg-black/90 p-4 rounded-lg border border-white/5 my-2">
              <MathEquation formula="\frac{\partial^2 \psi}{\partial t^2} = c^2 \nabla^2 \psi - 2\gamma \frac{\partial \psi}{\partial t}" />
            </div>
            <div className="text-[11px] text-slate-500 space-y-1 pt-1 font-mono">
              <div>Phase velocity: c = 1.15 m/s</div>
              <div>Viscous damping: γ = 0.045</div>
            </div>
          </div>

          {/* Equation 2: Parametric Fourier Superposition */}
          <div className="bg-white/[0.02] border border-white/[0.08] p-6 rounded-xl space-y-3 font-mono text-xs">
            <div className="text-[10px] text-slate-400 uppercase tracking-widest border-b border-white/10 pb-2 flex justify-between font-mono">
              <span>THEOREM 2.0</span>
              <span className="text-purple-400">FOURIER HARMONIC SUM</span>
            </div>
            <p className="text-slate-300 font-sans leading-relaxed text-xs">
              Elevation of ribbon k ∈ [0, 14] with spatial Gaussian damping α = 0.016 and 4 harmonic Fourier modes:
            </p>
            <div className="bg-black/90 p-4 rounded-lg border border-white/5 my-2">
              <MathEquation formula="\psi(x, t, k) = e^{-\alpha x^2} \sum_{m=1}^{M=4} A_m \sin\left(\omega_m x - \omega t + k \Delta\theta_m\right)" />
            </div>
            <div className="text-[11px] text-slate-500 space-y-1 pt-1 font-mono">
              <div>Weights: A_m ∈ &#123;1.35, 0.65, 0.32, 0.16&#125;</div>
              <div>Spatial frequencies: ω_m ∈ &#123;0.38, 0.92, 1.85, 3.40&#125; rad/m</div>
            </div>
          </div>

          {/* Equation 3: Pointer Phase Interference */}
          <div className="bg-white/[0.02] border border-white/[0.08] p-6 rounded-xl space-y-3 font-mono text-xs">
            <div className="text-[10px] text-slate-400 uppercase tracking-widest border-b border-white/10 pb-2 flex justify-between font-mono">
              <span>THEOREM 3.0</span>
              <span className="text-emerald-400">POINTER INTERFERENCE NODE</span>
            </div>
            <p className="text-slate-300 font-sans leading-relaxed text-xs">
              Localized dynamic perturbation generated by raycast cursor coordinates r_ptr = (x_p, z_p):
            </p>
            <div className="bg-black/90 p-4 rounded-lg border border-white/5 my-2">
              <MathEquation formula="\Delta\psi_{\text{ptr}} = A_{\text{ptr}} \cdot e^{-\beta \|\mathbf{r} - \mathbf{r}_{\text{ptr}}\|} \cdot \sin\left(k_{\text{ptr}} \|\mathbf{r} - \mathbf{r}_{\text{ptr}}\| - 3.5 t\right)" />
            </div>
            <div className="text-[11px] text-slate-500 space-y-1 pt-1 font-mono">
              <div>Spatial decay rate: β = 0.45</div>
              <div>Radial wavenumber: k_ptr = 2.2</div>
            </div>
          </div>

          {/* Equation 4: Statistical Cumulants */}
          <div className="bg-white/[0.02] border border-white/[0.08] p-6 rounded-xl space-y-3 font-mono text-xs">
            <div className="text-[10px] text-slate-400 uppercase tracking-widest border-b border-white/10 pb-2 flex justify-between font-mono">
              <span>THEOREM 4.0</span>
              <span className="text-cyan-400">STATISTICAL CUMULANTS (AMC)</span>
            </div>
            <p className="text-slate-300 font-sans leading-relaxed text-xs">
              Carrier-independent blind modulation moments computed from normalized complex I/Q symbols:
            </p>
            <div className="bg-black/90 p-4 rounded-lg border border-white/5 my-2">
              <MathEquation formula="C_{40} = M_{40} - 3M_{20}^2, \quad C_{42} = M_{42} - |M_{20}|^2 - 2M_{21}^2" />
            </div>
            <div className="text-[11px] text-slate-500 space-y-1 pt-1 font-mono">
              <div>BPSK theoretical: C₄₀ = -2.0, C₄₂ = 1.0</div>
              <div>QPSK theoretical: C₄₀ = -1.0, C₄₂ = 1.0</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
